import './globals.css'
import type { Metadata } from 'next'

import { Providers } from '@/app/providers'
import { Layout } from '@/components/Layout/Layout'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
                                     children,
                                   }: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="h-full antialiased" suppressHydrationWarning>
    <body className="flex h-full bg-zinc-50 dark:bg-black">
    <Providers>
      <div className="flex w-full">
        <Layout>{children}</Layout>
      </div>
    </Providers>
    </body>
    </html>
  )
}
